# Generated by Django 3.0.3 on 2020-03-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
